@HostAddres = http://localhost:5158/api

### GET pegar uma Categoria
GET {{HostAddres}}/categories/8003
Accept: application/json

### GET pegar todas as Categorias
GET {{HostAddres}}/categories/
Accept: application/json

### POST criar uma Categoria
POST {{HostAddres}}/categories/
Content-Type: application/json
Accept: application/json

{
  "Name": "Português",
  "Description": "Categoria de português para ensino fundamental 1 e 2",
  "urlImage": "/images/default.jpeg",
  "Status": "Active",
  "UserId": 20
}

### PUT atualizar uma categoria
PUT {{HostAddres}}/categories/1
Content-Type: application/json
Accept: application/json

  {
    "Name": "mattt",
    "Description": "Categoria ",
    "UrlImage": "/images/default.jpeg",
    "Status": "Active",
    "UserId": 1
  }

### DELETE remover uma categoria
DELETE {{HostAddres}}/categories/1006
Accept: application/json   


