@HostAddres = http://localhost:5158/api

### GET Pegar um usuário específico
GET {{HostAddres}}/users/1
Accept: application/json

### GET Pegar todos os usuários
GET {{HostAddres}}/users
Accept: application/json

### POST criar um novo usuário
POST {{HostAddres}}/users/
Content-Type: application/json
Accept: application/json

{
  "Name": "jose",
  "Email": "josejamersonmt@gmail.com",
  "UserType": "Teacher" 
}

### PUT atualizar um usuário
PUT {{HostAddres}}/users/1
Content-Type: application/json

{
    "Name": "José Jamerson",
    "Email": "jjmt@gmail.com",
    "UserType": "Admin" // Altere conforme o seu enum de status
}

### DELETE remover um usuário
DELETE {{HostAddres}}/users/1
Accept: application/json   

