# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  capacitadigitalapi:
    image: capacitadigitalapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5158:5158
    depends_on:
      - sqlserver

  sqlserver:
      image: mcr.microsoft.com/mssql/server:2022-latest
      environment:
        SA_PASSWORD: "@Sql21301"
        ACCEPT_EULA: "Y"
      ports:
        - "1433:1433"