version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: jjmt
      POSTGRES_PASSWORD: "@Sql21301"
      POSTGRES_DB: capacitadigital
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=capacitadigital;Username=jjmt;Password=@Sql21301

volumes:
  postgres_data: